# Generated by Django 5.2 on 2025-04-23 02:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=30)),
                ('data_nascimento', models.DateField()),
                ('falecido', models.BooleanField(default=False)),
                ('biografia', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('século_origem', models.IntegerField()),
                ('popularidade', models.CharField(choices=[('A', 'Alta'), ('M', 'Média'), ('B', 'Baixa')], max_length=10)),
                ('subgenero', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('nome',), name='genero_unico')],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('paginas', models.IntegerField()),
                ('avaliacao', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.autor')),
                ('genero', models.ManyToManyField(to='mysite.genero')),
            ],
            options={
                'verbose_name': 'Livro',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('data_aquisicao', models.DateField(auto_now_add=True)),
                ('emprestado', models.BooleanField(default=False)),
                ('localizacao', models.CharField(max_length=10)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplares', to='mysite.livro')),
            ],
            options={
                'verbose_name': 'Exemplar',
                'verbose_name_plural': 'Exemplares',
            },
        ),
    ]
